In [1]:
import pandas as pd
import numpy as np

# Load Zillow data

In [3]:
df= pd.read_csv('zillow1.csv')
df.head()

,RegionID,SizeRank,RegionName,RegionType,StateName,State,City,Metro,CountyName,2000-01-31,...,2025-04-30,2025-05-31,2025-06-30,2025-07-31,2025-08-31,2025-09-30,2025-10-31,2025-11-30,2025-12-31,2026-01-31
0,91982,1,77494,zip,TX,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Fort Bend County,204988.368604,...,486136.109041,484000.352719,481473.267183,479455.235388,478365.621634,478562.451979,479293.472947,480341.632597,480930.867232,480543.633571
1,61148,2,8701,zip,NJ,NJ,Lakewood,"New York-Newark-Jersey City, NY-NJ-PA",Ocean County,111719.941374,...,529389.748384,532145.350705,534655.041351,536426.444429,537661.425723,540194.582941,545049.835219,550925.682161,557122.838698,561559.028597
2,91940,3,77449,zip,TX,TX,Katy,"Houston-The Woodlands-Sugar Land, TX",Harris County,102728.188083,...,274073.754470,273277.617577,272287.601139,271356.056827,270430.150384,269659.092826,268926.643529,268297.386452,267961.720785,267417.889737
3,62080,4,11368,zip,NY,NY,New York,"New York-Newark-Jersey City, NY-NJ-PA",Queens County,172864.490023,...,528122.229315,528512.439633,530570.039974,533309.674869,534970.696579,536204.071877,537227.467932,539139.357023,541823.178015,546584.297355
4,91733,5,77084,zip,TX,TX,Houston,"Houston-The Woodlands-Sugar Land, TX",Harris County,102246.148663,...,270027.619313,269137.452625,268139.369611,267230.225642,266357.802018,265483.654722,264636.773995,263910.190406,263568.203302,263066.097594

In [6]:
# Reorganize data:
import pandas as pd

date_cols = [c for c in df_zip.columns if "-" in c]  # date columns like 2013-01-31

panel_zip = df_zip.melt(
    id_vars=["RegionID", "RegionName", "State", "City", "CountyName"],
    value_vars=date_cols,
    var_name="date",
    value_name="price"
)

panel_zip["date"] = pd.to_datetime(panel_zip["date"])
panel_zip["year"] = panel_zip["date"].dt.year
panel_zip["month"] = panel_zip["date"].dt.month

In [7]:

date_cols = [c for c in df_zip.columns if "-" in c]  # date columns like 2013-01-31

panel_zip = df_zip.melt(
    id_vars=["RegionID", "RegionName", "State", "City", "CountyName"],
    value_vars=date_cols,
    var_name="date",
    value_name="price"
)

panel_zip["date"] = pd.to_datetime(panel_zip["date"])
panel_zip["year"] = panel_zip["date"].dt.year
panel_zip["month"] = panel_zip["date"].dt.month

In [8]:
panel_zip = panel_zip.rename(columns={"RegionName": "zip_code"})
panel_zip["zip_code"] = panel_zip["zip_code"].astype(str).str.zfill(5)

In [9]:

panel_zip = panel_zip[(panel_zip["year"] >= 2013) & (panel_zip["year"] <= 2023)].copy()

In [11]:
zip_year = (
    panel_zip
    .groupby(
        ["RegionID", "zip_code", "State", "City", "CountyName", "year"],
        as_index=False
    )
    .agg({"price": "mean"})
)

zip_year.head()

   RegionID zip_code State    City      CountyName  year          price
0     58196    01001    MA  Agawam  Hampden County  2013  179159.306814
1     58196    01001    MA  Agawam  Hampden County  2014  179950.420804
2     58196    01001    MA  Agawam  Hampden County  2015  181797.078539
3     58196    01001    MA  Agawam  Hampden County  2016  190231.359754
4     58196    01001    MA  Agawam  Hampden County  2017  197659.904419

In [12]:
zip_year_ca = zip_year[zip_year["State"] == "CA"]
zip_year_ca.head()

,RegionID,zip_code,State,City,CountyName,year,price
250008,95982,90001,CA,Florence-Graham,Los Angeles County,2013,184912.712009
250009,95982,90001,CA,Florence-Graham,Los Angeles County,2014,225886.255973
250010,95982,90001,CA,Florence-Graham,Los Angeles County,2015,253188.792513
250011,95982,90001,CA,Florence-Graham,Los Angeles County,2016,273868.654666
250012,95982,90001,CA,Florence-Graham,Los Angeles County,2017,315517.525062

# Load WFH data

In [13]:
import pandas as pd
import glob
import re
from pathlib import Path

folder = r"C:\Users\minht\Capstone new\WFHnew"

files = glob.glob(str(Path(folder) / "ACSST5Y*.S0801-Data.csv"))

dfs = []

for f in files:
    
    year = int(re.search(r"ACSST5Y(\d{4})\.S0801-Data\.csv", Path(f).name).group(1))

    d = pd.read_csv(
        f,
        usecols=["GEO_ID", "NAME", "S0801_C01_003E"],
        dtype=str,
        low_memory=False
    )

    d = d.rename(columns={"S0801_C01_003E": "wfh_share"})
    d["year"] = year

    dfs.append(d)

acs_wfh = pd.concat(dfs, ignore_index=True)

# Convert to numeric
acs_wfh["wfh_share"] = pd.to_numeric(acs_wfh["wfh_share"], errors="coerce")

# Extract ZIP from NAME like "ZCTA5 90001"
acs_wfh["zip"] = acs_wfh["NAME"].str.extract(r"(\d{5})")

# optional: keep only rows where ZIP exists
acs_wfh = acs_wfh[acs_wfh["zip"].notna()].copy()

acs_wfh["zip"] = acs_wfh["zip"].astype(str).str.zfill(5)
acs_wfh.head()

           GEO_ID         NAME  wfh_share  year    zip
1  8600000US89010  ZCTA5 89010       61.8  2013  89010
2  8600000US89019  ZCTA5 89019       57.8  2013  89019
3  8600000US89060  ZCTA5 89060       76.7  2013  89060
4  8600000US89061  ZCTA5 89061       75.7  2013  89061
5  8600000US89439  ZCTA5 89439       75.6  2013  89439

## Load population data

In [14]:
import pandas as pd
import glob
import re
from pathlib import Path

folder = r"C:\Users\minht\Capstone new\Popnew"

files = glob.glob(str(Path(folder) / "ACSDT5Y*.B01003-Data.csv"))

dfs = []

for f in files:
    
    year = int(re.search(r"ACSDT5Y(\d{4})\.B01003-Data\.csv", Path(f).name).group(1))

    d = pd.read_csv(
        f,
        usecols=["GEO_ID", "NAME", "B01003_001E"],
        dtype=str,
        low_memory=False
    )

    d = d.rename(columns={"B01003_001E": "population"})
    d["year"] = year

    dfs.append(d)

acs_pop = pd.concat(dfs, ignore_index=True)

# Convert to numeric
acs_pop["population"] = pd.to_numeric(acs_pop["population"], errors="coerce")

# Extract ZIP (ZCTA)
acs_pop["zip"] = acs_pop["NAME"].str.extract(r"(\d{5})")
acs_pop["zip"] = acs_pop["zip"].astype(str).str.zfill(5)

acs_pop = acs_pop.sort_values(["zip", "year"]).reset_index(drop=True)

acs_pop.head()

      GEO_ID                  NAME  population  year    zip
0  Geography  Geographic Area Name         NaN  2013  00nan
1  Geography  Geographic Area Name         NaN  2014  00nan
2  Geography  Geographic Area Name         NaN  2015  00nan
3  Geography  Geographic Area Name         NaN  2016  00nan
4  Geography  Geographic Area Name         NaN  2017  00nan

## Load Income Data

In [15]:
import pandas as pd
import glob
import re
from pathlib import Path

folder = r"C:\Users\minht\Capstone new\incomenew"

files = glob.glob(str(Path(folder) / "ACSDT5Y*.B19013-Data.csv"))

dfs = []

for f in files:
    
    year = int(re.search(r"ACSDT5Y(\d{4})\.B19013-Data\.csv", Path(f).name).group(1))

    d = pd.read_csv(
        f,
        usecols=["GEO_ID", "NAME", "B19013_001E"],
        dtype=str,
        low_memory=False
    )

    d = d.rename(columns={"B19013_001E": "median_income"})
    d["year"] = year

    dfs.append(d)

acs_income = pd.concat(dfs, ignore_index=True)

# Convert to numeric
acs_income["median_income"] = pd.to_numeric(acs_income["median_income"], errors="coerce")

# Extract ZIP from NAME (ZCTA format)
acs_income["zip"] = acs_income["NAME"].str.extract(r"(\d{5})")
acs_income["zip"] = acs_income["zip"].astype(str).str.zfill(5)

acs_income = acs_income.sort_values(["zip", "year"]).reset_index(drop=True)

acs_income.head()

      GEO_ID                  NAME  median_income  year    zip
0  Geography  Geographic Area Name            NaN  2013  00nan
1  Geography  Geographic Area Name            NaN  2014  00nan
2  Geography  Geographic Area Name            NaN  2015  00nan
3  Geography  Geographic Area Name            NaN  2016  00nan
4  Geography  Geographic Area Name            NaN  2017  00nan

## Merge all data by zip-code:

In [16]:
# Merge with WFH data
zip_year_ca = zip_year_ca.merge(
    acs_wfh[["zip", "year", "wfh_share"]],
    left_on=["zip_code", "year"],
    right_on=["zip", "year"],
    how="left"
)
zip_year_ca = zip_year_ca.drop(columns=["zip"])

In [18]:
# Merge with Population data
zip_year_ca = zip_year_ca.merge(
    acs_pop[["zip", "year", "population"]],
    left_on=["zip_code", "year"],
    right_on=["zip", "year"],
    how="left"
).drop(columns=["zip"])

In [19]:
# Merge with income data
zip_year_ca = zip_year_ca.merge(
    acs_income[["zip", "year", "median_income"]],
    left_on=["zip_code", "year"],
    right_on=["zip", "year"],
    how="left"
).drop(columns=["zip"])

In [20]:
# Check the quality of merging data:
zip_year_ca[["wfh_share","population","median_income"]].isna().mean()

wfh_share        0.004036
population       0.003253
median_income    0.021688
dtype: float64

In [21]:
# Visualize data: 
zip_year_ca.head()

,RegionID,zip_code,State,City,CountyName,year,price,wfh_share,population,median_income
0,95982,90001,CA,Florence-Graham,Los Angeles County,2013,184912.712009,64.6,54760.0,35097.0
1,95982,90001,CA,Florence-Graham,Los Angeles County,2014,225886.255973,64.1,56314.0,34050.0
2,95982,90001,CA,Florence-Graham,Los Angeles County,2015,253188.792513,63.8,57227.0,33887.0
3,95982,90001,CA,Florence-Graham,Los Angeles County,2016,273868.654666,65.5,57942.0,34323.0
4,95982,90001,CA,Florence-Graham,Los Angeles County,2017,315517.525062,66.0,58738.0,35660.0

In [23]:
zip_year_ca[[
    "price",
    "wfh_share",
    "median_income",
    "population"
]].isna().mean()

price            0.023857
wfh_share        0.004036
median_income    0.021688
population       0.003253
dtype: float64

In [25]:
import numpy as np

zip_year_ca["log_price"]  = np.log(zip_year_ca["price"])
zip_year_ca["log_income"] = np.log(zip_year_ca["median_income"])
zip_year_ca["log_pop"]    = np.log1p(zip_year_ca["population"])  # safe if zero exists

In [27]:
reg_vars = ["log_price", "wfh_share", "log_income", "log_pop", "zip_code", "year"]

reg_df = zip_year_ca.dropna(subset=reg_vars).copy()

reg_df.shape

(15868, 13)

In [33]:
import numpy as np

summary = reg_df[[
    "log_price",
    "wfh_share",
    "median_income",
    "population"
]].agg([
    "count",
    "mean",
    "std",
    "min",
    "median",
    "max"
]).T

summary

,count,mean,std,min,median,max
log_price,15868.0,13.082832,0.681897,10.560854,13.103557,15.50641
wfh_share,15868.0,72.081447,11.957440,0.000000,74.900000,100.00000
median_income,15868.0,77140.890471,35417.548010,6827.000000,69961.000000,247604.00000
population,15868.0,26549.123393,22100.672229,10.000000,24490.500000,111165.00000

In [37]:
import statsmodels.formula.api as smf

model = smf.ols(
    "log_price ~ wfh_share + median_income + population + C(zip_code) + C(year)",
    data=reg_df
).fit(
    cov_type="cluster",
    cov_kwds={"groups": reg_df["zip_code"]}
)

print(model.summary())

C:\Users\minht\anaconda3\Lib\site-packages\statsmodels\base\model.py:1894: ValueWarning: covariance of constraints does not have full rank. The number of constraints is 1513, but rank is 13
  warnings.warn('covariance of constraints does not have full '

                            OLS Regression Results
==============================================================================
Dep. Variable:              log_price   R-squared:                       0.990
Model:                            OLS   Adj. R-squared:                  0.989
Method:                 Least Squares   F-statistic:                 1.442e+05
Date:                Fri, 20 Feb 2026   Prob (F-statistic):               0.00
Time:                        21:28:16   Log-Likelihood:                 19873.
No. Observations:               15868   AIC:                        -3.672e+04
Df Residuals:                   14354   BIC:                        -2.510e+04
Df Model:                        1513
Covariance Type:              cluster
========================================================================================
                           coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept               12.1690      0.090    135.217      0.000      11.993      12.345
C(zip_code)[T.90002]    -0.0027      0.008     -0.321      0.748      -0.019       0.014
C(zip_code)[T.90003]     0.0038      0.021      0.184      0.854      -0.037       0.045
C(zip_code)[T.90004]     1.1086      0.006    190.349      0.000       1.097       1.120
C(zip_code)[T.90005]     0.8714      0.029     29.575      0.000       0.814       0.929
C(zip_code)[T.90006]     0.5367      0.005    106.350      0.000       0.527       0.547
C(zip_code)[T.90007]     0.4940      0.025     19.626      0.000       0.445       0.543
C(zip_code)[T.90008]     0.6807      0.039     17.588      0.000       0.605       0.757
C(zip_code)[T.90010]     1.0237      0.083     12.374      0.000       0.862       1.186
C(zip_code)[T.90011]    -0.0572      0.074     -0.771      0.440      -0.202       0.088
C(zip_code)[T.90012]     0.4496      0.035     12.694      0.000       0.380       0.519
C(zip_code)[T.90013]     0.5457      0.070      7.800      0.000       0.409       0.683
C(zip_code)[T.90014]     0.4664      0.077      6.088      0.000       0.316       0.617
C(zip_code)[T.90015]     0.7586      0.056     13.597      0.000       0.649       0.868
C(zip_code)[T.90016]     0.5271      0.017     31.411      0.000       0.494       0.560
C(zip_code)[T.90017]     0.7486      0.049     15.356      0.000       0.653       0.844
C(zip_code)[T.90018]     0.4780      0.010     46.169      0.000       0.458       0.498
C(zip_code)[T.90019]     0.9450      0.010     90.494      0.000       0.925       0.966
C(zip_code)[T.90020]     0.5843      0.029     20.425      0.000       0.528       0.640
C(zip_code)[T.90021]     0.8655      0.085     10.195      0.000       0.699       1.032
C(zip_code)[T.90022]     0.1880      0.014     13.912      0.000       0.162       0.214
C(zip_code)[T.90023]     0.1362      0.018      7.591      0.000       0.101       0.171
C(zip_code)[T.90024]     1.2056      0.013     94.203      0.000       1.180       1.231
C(zip_code)[T.90025]     1.0152      0.020     51.774      0.000       0.977       1.054
C(zip_code)[T.90026]     0.9289      0.015     62.924      0.000       0.900       0.958
C(zip_code)[T.90027]     1.3272      0.019     69.408      0.000       1.290       1.365
C(zip_code)[T.90028]     0.9293      0.042     22.074      0.000       0.847       1.012
C(zip_code)[T.90029]     0.8787      0.031     28.211      0.000       0.818       0.940
C(zip_code)[T.90031]     0.3946      0.029     13.661      0.000       0.338       0.451
C(zip_code)[T.90032]     0.3686      0.017     21.803      0.000       0.335       0.402
C(zip_code)[T.90033]     0.1895      0.015     13.003      0.000       0.161       0.218
C(zip_code)[T.90034]     1.0458      0.006    185.221      0.000       1.035       1.057
C(zip_code)[T.90035]     1.2965      0.045     28.908      0.000       1.209       1.384
C(zip_code)[T.90036]     1.4180      0.031     45.037      0.000       1.356       1.480
C(zip_code)[T.90037]     0.1599      0.011     14.003      0.000       0.138       0.182
C(zip_code)[T.90038]     1.0318      0.045     22.907      0.000       0.944       1.120
C(zip_code)[T.90039]     1.0532      0.045     23.335      0.000       0.965       1.142
C(zip_code)[T.90040]     0.2885      0.069      4.179      0.000       0.153       0.424
C(zip_code)[T.90041]     0.9280      0.045     20.604      0.000       0.840       1.016
C(zip_code)[T.90042]     0.5744      0.007     87.748      0.000       0.562       0.587
C(zip_code)[T.90043]     0.4217      0.020     20.637      0.000       0.382       0.462
C(zip_code)[T.90044]     0.0444      0.056      0.787      0.431      -0.066       0.155
C(zip_code)[T.90045]     1.0892      0.027     40.021      0.000       1.036       1.142
C(zip_code)[T.90046]     1.2343      0.012    100.265      0.000       1.210       1.258
C(zip_code)[T.90047]     0.2056      0.013     16.405      0.000       0.181       0.230
C(zip_code)[T.90048]     1.4197      0.056     25.495      0.000       1.311       1.529
C(zip_code)[T.90049]     1.8135      0.037     49.535      0.000       1.742       1.885
C(zip_code)[T.90056]     1.1155      0.076     14.638      0.000       0.966       1.265
C(zip_code)[T.90057]     0.3219      0.017     18.444      0.000       0.288       0.356
C(zip_code)[T.90058]     0.0377      0.083      0.451      0.652      -0.126       0.201
C(zip_code)[T.90059]     0.0481      0.022      2.184      0.029       0.005       0.091
C(zip_code)[T.90061]     0.1171      0.045      2.610      0.009       0.029       0.205
C(zip_code)[T.90062]     0.2668      0.036      7.319      0.000       0.195       0.338
C(zip_code)[T.90063]     0.1749      0.007     25.421      0.000       0.161       0.188
C(zip_code)[T.90064]     1.4313      0.050     28.850      0.000       1.334       1.529
C(zip_code)[T.90065]     0.7340      0.018     41.435      0.000       0.699       0.769
C(zip_code)[T.90066]     1.2011      0.006    193.010      0.000       1.189       1.213
C(zip_code)[T.90067]     1.4589      0.086     17.037      0.000       1.291       1.627
C(zip_code)[T.90068]     1.3251      0.056     23.626      0.000       1.215       1.435
C(zip_code)[T.90069]     1.2119      0.058     20.917      0.000       1.098       1.325
C(zip_code)[T.90077]     2.0287      0.080     25.355      0.000       1.872       2.186
C(zip_code)[T.90094]     1.2333      0.076     16.129      0.000       1.083       1.383
C(zip_code)[T.90201]     0.0708      0.065      1.087      0.277      -0.057       0.198
C(zip_code)[T.90210]     2.4513      0.061     40.505      0.000       2.333       2.570
C(zip_code)[T.90211]     1.5977      0.076     21.046      0.000       1.449       1.746
C(zip_code)[T.90212]     1.9191      0.070     27.261      0.000       1.781       2.057
C(zip_code)[T.90220]     0.0839      0.011      7.834      0.000       0.063       0.105
C(zip_code)[T.90221]     0.0899      0.008     10.823      0.000       0.074       0.106
C(zip_code)[T.90222]     0.0628      0.038      1.651      0.099      -0.012       0.137
C(zip_code)[T.90230]     0.8271      0.039     21.110      0.000       0.750       0.904
C(zip_code)[T.90232]     1.3034      0.065     19.946      0.000       1.175       1.431
C(zip_code)[T.90240]     0.6459      0.049     13.253      0.000       0.550       0.741
C(zip_code)[T.90241]     0.5356      0.021     25.104      0.000       0.494       0.577
C(zip_code)[T.90242]     0.4257      0.024     17.881      0.000       0.379       0.472
C(zip_code)[T.90245]     1.2637      0.064     19.888      0.000       1.139       1.388
C(zip_code)[T.90247]     0.3280      0.015     21.272      0.000       0.298       0.358
C(zip_code)[T.90248]     0.4808      0.071      6.730      0.000       0.341       0.621
C(zip_code)[T.90249]     0.4393      0.048      9.187      0.000       0.346       0.533
C(zip_code)[T.90250]     0.4485      0.059      7.653      0.000       0.334       0.563
C(zip_code)[T.90254]     1.5908      0.060     26.337      0.000       1.472       1.709
C(zip_code)[T.90255]     0.1224      0.026      4.781      0.000       0.072       0.173
C(zip_code)[T.90260]     0.4616      0.035     13.086      0.000       0.392       0.531
C(zip_code)[T.90262]     0.1510      0.018      8.382      0.000       0.116       0.186
C(zip_code)[T.90265]     1.9534      0.064     30.320      0.000       1.827       2.080
C(zip_code)[T.90266]     1.9261      0.039     48.877      0.000       1.849       2.003
C(zip_code)[T.90270]     0.1869      0.047      3.966      0.000       0.095       0.279
C(zip_code)[T.90272]     2.0714      0.060     34.753      0.000       1.955       2.188
C(zip_code)[T.90274]     1.7588      0.055     32.130      0.000       1.651       1.866
C(zip_code)[T.90275]     1.3374      0.029     46.399      0.000       1.281       1.394
C(zip_code)[T.90277]     1.2342      0.036     33.930      0.000       1.163       1.305
C(zip_code)[T.90278]     1.0578      0.029     36.861      0.000       1.002       1.114
C(zip_code)[T.90280]     0.1443      0.056      2.577      0.010       0.035       0.254
C(zip_code)[T.90290]     1.1899      0.081     14.748      0.000       1.032       1.348
C(zip_code)[T.90291]     1.6520      0.048     34.154      0.000       1.557       1.747
C(zip_code)[T.90292]     1.2344      0.055     22.457      0.000       1.127       1.342
C(zip_code)[T.90293]     0.9283      0.070     13.317      0.000       0.792       1.065
C(zip_code)[T.90301]     0.1669      0.031      5.370      0.000       0.106       0.228
C(zip_code)[T.90302]     0.2335      0.042      5.533      0.000       0.151       0.316
C(zip_code)[T.90303]     0.3774      0.050      7.485      0.000       0.279       0.476
C(zip_code)[T.90304]     0.3361      0.048      7.040      0.000       0.243       0.430
C(zip_code)[T.90305]     0.4658      0.065      7.152      0.000       0.338       0.593
C(zip_code)[T.90401]     1.4291      0.078     18.415      0.000       1.277       1.581
C(zip_code)[T.90402]     2.3316      0.073     31.930      0.000       2.188       2.475
C(zip_code)[T.90403]     1.4037      0.052     27.064      0.000       1.302       1.505
C(zip_code)[T.90404]     0.9911      0.054     18.287      0.000       0.885       1.097
C(zip_code)[T.90405]     1.4587      0.046     31.450      0.000       1.368       1.550
C(zip_code)[T.90501]     0.7149      0.024     30.253      0.000       0.669       0.761
C(zip_code)[T.90502]     0.3902      0.061      6.384      0.000       0.270       0.510
C(zip_code)[T.90503]     0.8988      0.021     42.005      0.000       0.857       0.941
C(zip_code)[T.90504]     0.6701      0.038     17.408      0.000       0.595       0.746
C(zip_code)[T.90505]     1.0297      0.033     31.072      0.000       0.965       1.095
C(zip_code)[T.90601]     0.5101      0.039     13.050      0.000       0.433       0.587
C(zip_code)[T.90602]     0.5003      0.048     10.395      0.000       0.406       0.595
C(zip_code)[T.90603]     0.6278      0.058     10.914      0.000       0.515       0.740
C(zip_code)[T.90604]     0.4252      0.027     15.924      0.000       0.373       0.478
C(zip_code)[T.90605]     0.4157      0.026     16.051      0.000       0.365       0.467
C(zip_code)[T.90606]     0.3825      0.039      9.848      0.000       0.306       0.459
C(zip_code)[T.90620]     0.5790      0.020     29.628      0.000       0.541       0.617
C(zip_code)[T.90621]     0.5498      0.034     16.172      0.000       0.483       0.616
C(zip_code)[T.90623]     0.8099      0.065     12.466      0.000       0.683       0.937
C(zip_code)[T.90630]     0.6744      0.016     42.257      0.000       0.643       0.706
C(zip_code)[T.90631]     0.5168      0.019     27.874      0.000       0.480       0.553
C(zip_code)[T.90638]     0.5293      0.017     32.004      0.000       0.497       0.562
C(zip_code)[T.90640]     0.4074      0.009     47.317      0.000       0.391       0.424
C(zip_code)[T.90650]     0.2216      0.072      3.064      0.002       0.080       0.363
C(zip_code)[T.90660]     0.2754      0.010     28.359      0.000       0.256       0.294
C(zip_code)[T.90670]     0.4028      0.063      6.410      0.000       0.280       0.526
C(zip_code)[T.90680]     0.3631      0.041      8.787      0.000       0.282       0.444
C(zip_code)[T.90701]     0.5048      0.063      8.010      0.000       0.381       0.628
C(zip_code)[T.90703]     0.7354      0.016     46.009      0.000       0.704       0.767
C(zip_code)[T.90704]     0.7980      0.084      9.519      0.000       0.634       0.962
C(zip_code)[T.90706]     0.3329      0.031     10.816      0.000       0.273       0.393
C(zip_code)[T.90710]     0.5313      0.046     11.598      0.000       0.442       0.621
C(zip_code)[T.90712]     0.5638      0.041     13.681      0.000       0.483       0.645
C(zip_code)[T.90713]     0.5998      0.046     13.068      0.000       0.510       0.690
C(zip_code)[T.90715]     0.4387      0.057      7.672      0.000       0.327       0.551
C(zip_code)[T.90716]     0.1519      0.066      2.288      0.022       0.022       0.282
C(zip_code)[T.90717]     0.6587      0.055     11.888      0.000       0.550       0.767
C(zip_code)[T.90720]     1.1109      0.055     20.305      0.000       1.004       1.218
C(zip_code)[T.90723]     0.0942      0.006     15.725      0.000       0.082       0.106
C(zip_code)[T.90731]     0.4882      0.007     68.494      0.000       0.474       0.502
C(zip_code)[T.90732]     0.6753      0.056     12.096      0.000       0.566       0.785
C(zip_code)[T.90740]     0.4090      0.051      8.014      0.000       0.309       0.509
C(zip_code)[T.90742]     1.6383      0.088     18.712      0.000       1.467       1.810
C(zip_code)[T.90744]     0.2189      0.003     81.769      0.000       0.214       0.224
C(zip_code)[T.90745]     0.3495      0.007     48.468      0.000       0.335       0.364
C(zip_code)[T.90746]     0.4803      0.048     10.090      0.000       0.387       0.574
C(zip_code)[T.90755]     0.4814      0.071      6.800      0.000       0.343       0.620
C(zip_code)[T.90802]     0.0675      0.028      2.403      0.016       0.012       0.123
C(zip_code)[T.90803]     1.0093      0.040     24.932      0.000       0.930       1.089
C(zip_code)[T.90804]     0.2814      0.028     10.059      0.000       0.227       0.336
C(zip_code)[T.90805]     0.1309      0.058      2.266      0.023       0.018       0.244
C(zip_code)[T.90806]     0.3791      0.024     15.747      0.000       0.332       0.426
C(zip_code)[T.90807]     0.6548      0.038     17.031      0.000       0.579       0.730
C(zip_code)[T.90808]     0.7173      0.030     23.532      0.000       0.658       0.777
C(zip_code)[T.90810]     0.2622      0.032      8.279      0.000       0.200       0.324
C(zip_code)[T.90813]     0.0722      0.002     41.057      0.000       0.069       0.076
C(zip_code)[T.90814]     0.7251      0.059     12.290      0.000       0.609       0.841
C(zip_code)[T.90815]     0.6923      0.026     26.144      0.000       0.640       0.744
C(zip_code)[T.91001]     0.9102      0.033     27.552      0.000       0.845       0.975
C(zip_code)[T.91006]     1.1237      0.040     28.052      0.000       1.045       1.202
C(zip_code)[T.91007]     1.1737      0.037     31.756      0.000       1.101       1.246
C(zip_code)[T.91008]     1.5767      0.088     17.990      0.000       1.405       1.749
C(zip_code)[T.91010]     0.4696      0.048      9.708      0.000       0.375       0.564
C(zip_code)[T.91011]     1.6657      0.061     27.108      0.000       1.545       1.786
C(zip_code)[T.91016]     0.7201      0.025     28.514      0.000       0.671       0.770
C(zip_code)[T.91020]     0.8023      0.075     10.647      0.000       0.655       0.950
C(zip_code)[T.91024]     1.1381      0.072     15.753      0.000       0.996       1.280
C(zip_code)[T.91030]     1.1715      0.050     23.608      0.000       1.074       1.269
C(zip_code)[T.91040]     0.5958      0.058     10.341      0.000       0.483       0.709
C(zip_code)[T.91042]     0.5495      0.047     11.763      0.000       0.458       0.641
C(zip_code)[T.91101]     0.6298      0.057     11.110      0.000       0.519       0.741
C(zip_code)[T.91103]     0.7564      0.047     16.202      0.000       0.665       0.848
C(zip_code)[T.91104]     0.8464      0.031     27.145      0.000       0.785       0.907
C(zip_code)[T.91105]     1.3715      0.071     19.188      0.000       1.231       1.512
C(zip_code)[T.91106]     0.7757      0.051     15.171      0.000       0.675       0.876
C(zip_code)[T.91107]     0.9901      0.040     24.819      0.000       0.912       1.068
C(zip_code)[T.91108]     1.9593      0.071     27.634      0.000       1.820       2.098
C(zip_code)[T.91201]     0.8746      0.053     16.505      0.000       0.771       0.978
C(zip_code)[T.91202]     0.8335      0.053     15.633      0.000       0.729       0.938
C(zip_code)[T.91203]     0.4993      0.065      7.660      0.000       0.372       0.627
C(zip_code)[T.91204]     0.4540      0.061      7.481      0.000       0.335       0.573
C(zip_code)[T.91205]     0.4826      0.031     15.485      0.000       0.422       0.544
C(zip_code)[T.91206]     0.7608      0.037     20.545      0.000       0.688       0.833
C(zip_code)[T.91207]     1.1791      0.072     16.307      0.000       1.037       1.321
C(zip_code)[T.91208]     1.1250      0.065     17.405      0.000       0.998       1.252
C(zip_code)[T.91210]     1.1041      0.089     12.350      0.000       0.929       1.279
C(zip_code)[T.91214]     0.9317      0.042     22.291      0.000       0.850       1.014
C(zip_code)[T.91301]     0.9724      0.051     19.044      0.000       0.872       1.072
C(zip_code)[T.91302]     1.4081      0.051     27.519      0.000       1.308       1.508
C(zip_code)[T.91303]     0.3361      0.043      7.852      0.000       0.252       0.420
C(zip_code)[T.91304]     0.6026      0.008     79.489      0.000       0.588       0.617
C(zip_code)[T.91306]     0.4141      0.014     29.664      0.000       0.387       0.441
C(zip_code)[T.91307]     0.7949      0.050     15.876      0.000       0.697       0.893
C(zip_code)[T.91311]     0.6362      0.029     22.134      0.000       0.580       0.693
C(zip_code)[T.91316]     0.6640      0.044     15.160      0.000       0.578       0.750
C(zip_code)[T.91320]     0.8239      0.024     34.636      0.000       0.777       0.871
C(zip_code)[T.91321]     0.3486      0.036      9.674      0.000       0.278       0.419
C(zip_code)[T.91324]     0.6234      0.044     14.274      0.000       0.538       0.709
C(zip_code)[T.91325]     0.6564      0.036     18.136      0.000       0.585       0.727
C(zip_code)[T.91326]     0.9205      0.035     26.289      0.000       0.852       0.989
C(zip_code)[T.91331]     0.1416      0.068      2.067      0.039       0.007       0.276
C(zip_code)[T.91335]     0.3094      0.032      9.592      0.000       0.246       0.373
C(zip_code)[T.91340]     0.2643      0.034      7.794      0.000       0.198       0.331
C(zip_code)[T.91342]     0.2889      0.055      5.246      0.000       0.181       0.397
C(zip_code)[T.91343]     0.4241      0.011     40.214      0.000       0.403       0.445
C(zip_code)[T.91344]     0.6278      0.011     58.915      0.000       0.607       0.649
C(zip_code)[T.91345]     0.4470      0.060      7.458      0.000       0.330       0.564
C(zip_code)[T.91350]     0.5690      0.032     17.827      0.000       0.506       0.632
C(zip_code)[T.91351]     0.3453      0.039      8.834      0.000       0.269       0.422
C(zip_code)[T.91352]     0.3772      0.017     22.165      0.000       0.344       0.411
C(zip_code)[T.91354]     0.6712      0.043     15.703      0.000       0.587       0.755
C(zip_code)[T.91355]     0.5273      0.041     12.802      0.000       0.447       0.608